version: '3.8'

services:
  aiconvertor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: filetransformerai_app
    volumes:
      - ./input_files:/app/input_files
      - ./output_files:/app/output_files
      - ./models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    networks:
      - aiconvertor_network

networks:
  aiconvertor_network:
    driver: bridge
